[project]
name = "gemini-chatbot"
version = "0.2.0"
description = "A chatbot application using Google's Gemini API and Streamlit."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "google-genai>=1.47.0",
    "streamlit>=1.49.1",
]
